### ISSUE TITLE
internal checkbox for obts being out of order

### ISSUE THREAD

**Issue by tamihuber** [paulwinterbauer/NBIC#92] opened 2022-04-05 14:17 UTC
example - http://serc4.si.edu:8001/NBIC/review/2826023/

It would be helpful to have a box we could check (Maybe in email review area? since sometimes obts review doesn't come up when it's auto-standardized) which would negate the obts error response from going out  (for those reports that have criteria for obts error response).

**Comment by paulwinterbauer** [comment] 2022-04-05 19:18
duplicate of #66

**Closed as completed by paulwinterbauer** 2022-04-05 19:18 UTC
Labels: duplicate
